redesign, REST API support
SkoltechSummerCamp/SpeedtestApplication pull request #16
Opened 2021-08-17 14:32 UTC by nikonufrienko

2021-08-17 16:58 UTC, AdvancerMan requested changes

2021-08-17 16:58 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +    }
Уже обсуждали. Вместо флажка лучше делать [`wait`](https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#wait--) + [`notify`](https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#notify--), либо использовать [`Lock`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/locks/Lock.html) и [`Condition`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/locks/Condition.html) -- более современный способ, чтобы сделать то же самое.

2021-08-17 16:58 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        })
Я не уверен, будут ли тут проблемы с видимостью переменной `result` (гугление подсказывает, что нет), но если ты сделаешь историю с `wait` + `notify` (или с `Condition`), то все точно будет ок.

2021-08-17 16:58 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/MainActivity.kt
> +        private val PING_SERVER_UDP_PORT = 49121
Я все еще считаю, что порт должен быть константой сервера

2021-08-17 16:58 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/MainActivity.kt
> +        enum class RequestType { START, STOP }
Классы не обязательно складывать в `companion object`. Также, имхо, `RequestType` должен лежать рядом с тем, кто его использует (`sendGETRequest`).

2021-08-17 16:58 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/MainActivity.kt
> +        private val PING_SERVER_UDP_PORT = 49121
А еще: для примитивов в `companion object` можно добавить модификатор `const`.

2021-08-17 16:58 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/MainActivity.kt
> +    private val context = this
Не очень понятно, зачем в активити хранить самого себя. Если при передаче как аргумент, хочешь подчеркнуть, что передаешь `context`, лучше передавать как именованый аргумент. Например, `foo(context = this)`

2021-08-17 16:58 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +    }
Сорри, `wait` + `notify` блокирует поток. Для корутин можно сделать [так](https://stackoverflow.com/questions/53906195/suspend-coroutine-until-condition-is-true), но не уверен, что это будет потокобезопасно

2021-08-17 16:58 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +            Log.d("get:", "Error \n $url \n $it")
А еще: логичнее здесь вызывать `Log.e()`

2021-08-17 16:58 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/MainActivity.kt
> +        binding.icmpPingButt.text = getString(R.string.bigStop)
Имхо, `Butt` -- не самый лучший нейминг. Лучше `Button`

2021-08-17 16:58 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/MainActivity.kt
> +        print("checking ip")
Я подозреваю, что все `print`'ы надо убрать

2021-08-17 22:02 UTC, nikonufrienko commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        MainActivity.Companion.RequestType.START -> "http://$address:5000/start-iperf?args=$value"
В смысле, escape'ить? Вроде как оно само безопасно либой инкодится в нужный формат. По крайней мере оно работает (я по разному пробовал). Неверные аргументы сервак просто не запустит, выдав ошибку.

2021-08-17 22:03 UTC, nikonufrienko commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        MainActivity.Companion.RequestType.START -> "http://$address:5000/start-iperf?args=$value"
Для порта сделаю компаньон-константу.

2021-08-18 10:11 UTC, nikonufrienko commented on app/src/main/java/ru/scoltech/openran/speedtest/MainActivity.kt
> +    private val context = this
Там проблемы с видимостью (`this` указывает на анонимный класс вроде).

2021-08-18 10:27 UTC, nikonufrienko commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        })
Проблем с видимостью быть однозначно не должно (меня даже на экзамене об этом спрашивали, как об одном из приемуществ котлина над джавой). На wait и notify щас исправлю.

2021-08-18 10:34 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/MainActivity.kt
> +    private val context = this
Понял, о чем ты. В таких случаях можно использовать [qualified this](https://kotlinlang.org/docs/this-expressions.html#qualified-this). Здесь это будет выглядеть так: `this@MainActivity`

2021-08-18 10:41 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        })
Скинь, пожалуйста, ссылку, где упоминается это преимущество.

По поводу `wait` и `notify` повторюсь: они блокируют поток. Почитай, как сделать аналогичное поведение с помощью [CompletableDeferred](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-completable-deferred/index.html)

2021-08-18 10:41 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +    }
Только что прочитал, что это будет потокобезопасно. Все ок

2021-08-18 10:50 UTC, nikonufrienko commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        })
Правда непонятно как отслеживать timeout при этом.

2021-08-18 11:23 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        MainActivity.Companion.RequestType.START -> "http://$address:5000/start-iperf?args=$value"
Ладно, валидировать можно на сервере, согласен.

Про порт: почему он константа? Если я правильно понимаю, юзер сам запускает сервер на своей машине (раз он задает адрес). Вдруг порт `5000` занят и освобождать его очень не хочется?

2021-08-18 22:54 UTC, nikonufrienko commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        })
В котлине вместо await и notify используются [каналы](https://kotlinlang.org/docs/channels.html).

2021-08-19 08:30 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        })
Про проблемы с видимостью увидел [вот такое](https://youtrack.jetbrains.com/issue/KT-14746) -- это означает, что уже как 5 лет это не преимущество котлина

2021-08-19 08:49 UTC, AdvancerMan requested changes

2021-08-19 08:49 UTC, AdvancerMan commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Зачем эта зависимость?

2021-08-19 08:49 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +    context: Context,
Parameter 'context' is never used

2021-08-19 08:49 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        RequestType.STOP -> "http://$address:${ApplicationConstants.HTTP_SERVER_PORT}/stop-iperf"
Все же ескейпить (или валидировать) на клиенте надо. Например, в `address` может попасть `:` -- сломается ли запрос от этого? Также при запросах браузеры (про запрос через джаву сомневаюсь ответить) не отправляют anchor, т. е. то, что идет после `#` -- сервер не получит все данные

2021-08-19 08:49 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        RequestType.STOP -> "http://$address:${ApplicationConstants.HTTP_SERVER_PORT}/stop-iperf"
Или, например, `address = "server.com/server/lol?args="` -- в этом случае угадать, как юзер хотел заескейпить трудно

2021-08-19 08:49 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +            channel.trySend(String(connection.getInputStream().readBytes(), StandardCharsets.UTF_8))
Не закрываешь `InputStream`

2021-08-19 08:49 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        channel.trySend("error")
Утечка ресурсов -- не закрываешь подключение по таймауту

2021-08-19 08:49 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        }
Возможно, здесь стоит отправить ошибку в канал, чтобы не ждать таймаут

2021-08-19 08:51 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        RequestType.STOP -> "http://$address:${ApplicationConstants.HTTP_SERVER_PORT}/stop-iperf"
И почему запрос по `http`, а не по `https`?

2021-08-19 12:09 UTC, nikonufrienko commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        RequestType.STOP -> "http://$address:${ApplicationConstants.HTTP_SERVER_PORT}/stop-iperf"
Потому что сервер https не поддерживает.

2021-08-19 13:41 UTC, AdvancerMan requested changes

2021-08-19 13:41 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +): String {
Android Studio подсказывает мне, что в этой функции происходит много `Inappropriate blocking method call `. Немного почитав про `Dispatchers.IO`, я понял, что все ок. Поставь, пожалуйста, `@Suppress("BlockingMethodInNonBlockingContext")` на функцию, а рядом комментарий, что так и должно быть.

2021-08-19 13:41 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +                currentPort = addressAndPort[1].toInt()
Не валидируешь инт

2021-08-19 13:41 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +                currentPort = addressAndPort[1].toInt()
Не валидируешь инт

2021-08-19 13:41 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +            else -> InetAddress.getByName("localhost")
Имхо, лучше сказать пользователю, что он не прав, а не посылать на локалхост

2021-08-19 13:41 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +            try{connection.inputStream.close()}catch (e: IOException){}
`connection.inputStream.use { channel.trySend(...) }`

2021-08-19 13:41 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        connection.disconnect()
Дисконнектить надо в `finally` блоке

2021-08-19 13:41 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        connection.disconnect()
А еще в [документации](https://developer.android.com/reference/kotlin/java/net/HttpURLConnection) написано, что `disconnect` освобождает все ресурсы, поэтому можно не закрывать `inputStream`

2021-08-19 13:41 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +            try{connection.inputStream.close()}catch (e: IOException){}
Ниже написал, почему можно не закрывать `inputStream`

2021-08-19 13:41 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +    timeout: Int,
Почему бы не принимать `timeout` сразу как `Long`?

2021-08-19 13:41 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        Log.d("url", url)
Теги лучше называть более конкретно (чтобы понимать, откуда пишется). Например, можно по названию метода/класса

2021-08-19 13:41 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        RequestType.STOP -> "http://$currentAddress:${currentPort}/stop-iperf"
Видимо, должно быть `currentAddress.hostAddress`

2021-08-19 13:41 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +            channel.trySend("error")
А еще имеет смысл уточнить, что за ошибка. Например, добавить в вывод `e.message`

2021-08-19 14:51 UTC, nikonufrienko commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        RequestType.STOP -> "http://$currentAddress:${currentPort}/stop-iperf"
Ок, странно, но оно у меня и так работало.

2021-08-19 14:53 UTC, nikonufrienko commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +            channel.trySend("error")
И да и нет, функция в случае ошибки должна возвращать только "error". Так что запихаю это в логи.

2021-08-19 17:01 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +            Log.d("get:", "Error \n $url \n $it")
ok

2021-08-19 17:01 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +    }
ok

2021-08-19 17:01 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        })
ok

2021-08-19 17:01 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/MainActivity.kt
> +        private val PING_SERVER_UDP_PORT = 49121
ok

2021-08-19 17:02 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/MainActivity.kt
> +        enum class RequestType { START, STOP }
ok

2021-08-19 17:02 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/MainActivity.kt
> +    private val context = this
ok

2021-08-19 17:02 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/MainActivity.kt
> +        binding.icmpPingButt.text = getString(R.string.bigStop)
ok

2021-08-19 17:02 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/MainActivity.kt
> +        print("checking ip")
ok

2021-08-19 17:03 UTC, AdvancerMan commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
ok

2021-08-19 17:03 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +    context: Context,
ok

2021-08-19 17:14 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +            channel.trySend(String(connection.getInputStream().readBytes(), StandardCharsets.UTF_8))
ok

2021-08-19 17:14 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        channel.trySend("error")
ok

2021-08-19 17:22 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        MainActivity.Companion.RequestType.START -> "http://$address:5000/start-iperf?args=$value"
ok

2021-08-19 17:22 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        RequestType.STOP -> "http://$address:${ApplicationConstants.HTTP_SERVER_PORT}/stop-iperf"
ok

2021-08-19 17:24 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        }
ok

2021-08-19 17:24 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +            try{connection.inputStream.close()}catch (e: IOException){}
ok

2021-08-19 17:24 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        connection.disconnect()
ok

2021-08-19 17:25 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +    timeout: Int,
ok

2021-08-19 17:25 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        Log.d("url", url)
ok

2021-08-19 17:25 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +        RequestType.STOP -> "http://$currentAddress:${currentPort}/stop-iperf"
ok

2021-08-19 17:26 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +            channel.trySend("error")
Лучше запихать в логи, которые видны юзеру

2021-08-19 17:37 UTC, nikonufrienko commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +            channel.trySend("error")
А это какие?

2021-08-19 17:40 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +                currentPort = addressAndPort[1].toInt()
ok

2021-08-19 17:41 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +                currentPort = addressAndPort[1].toInt()
ok

2021-08-19 17:43 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +            channel.trySend("error")
Которые видны в интерфейсе. Скорее всего возвращаемый тип надо поменять на некий `Result`, в который сложить все ошибки.

2021-08-19 17:45 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +            else -> InetAddress.getByName("localhost")
Тут лучше бы вернуть ошибку вида "неверный адрес"

2021-08-19 17:51 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +            channel.trySend("error")
У котлина на такой случай уже [есть](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-result/) реализация `Result`

2021-08-19 17:54 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +            channel.trySend("error")
Сорри, она не умеет в failure без исключения

2021-08-20 07:49 UTC, nikonufrienko commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +            else -> InetAddress.getByName("localhost")
Я же писал, что только "error" может быть возвращен. Я не хочу на выходе обрабатывать 100500 различных случаев.

2021-08-20 08:08 UTC, merged

2021-08-20 08:35 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +            else -> InetAddress.getByName("localhost")
На выходе будет только 2 случая: успех с сообщением с сервера, либо ошибка с сообщением, в чем ошибка

2021-08-20 08:35 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +): String {
Вообще лучше в комментарии уточнить, почему все ок

2021-08-20 09:00 UTC, nikonufrienko commented on app/src/main/java/ru/scoltech/openran/speedtest/sendGETRequest.kt
> +            else -> InetAddress.getByName("localhost")
Т.е. мне сделать на выходе Pair<String,String>. Первое -- сообщение, второе -- описание ошибки.