Join activities and add saving result as image
SkoltechSummerCamp/SpeedtestApplication pull request #21
Opened 2021-08-22 09:29 UTC by CatherineChernogor

Add redesigned activity, fix header buttons, join together activities and add activity switching by header and add saving and generating image

2021-08-22 11:11 UTC, AdvancerMan requested changes

2021-08-22 11:11 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/customButtons/SaveButton.java
> +        return new File(dir.getPath() + File.separator + imageName);
Конкатенировать путь можно так `dir.getPath().resolve(imageName).toFile()`

2021-08-22 11:11 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/customViews/CardView.java
> +    String mStatus;
`private`?

2021-08-22 11:11 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/customViews/CardView.java
> +    }
Зачем?

2021-08-22 11:11 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/customViews/CardView.java
> +        mbpsCaption.setText("Mbps");
Скорость не всегда в `Mbps`. То есть иногда приятнее выглядит `12 Kbps` и `1.2 Gbps` вместо `0.012 Mbps` и `12000 Mbps`.

2021-08-22 11:11 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/customViews/HeaderView.java
> +        });
Лямбды

2021-08-22 11:11 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/uml.puml
> +
Зачем этот файл?

2021-08-22 11:11 UTC, AdvancerMan commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:4.0.2'
Gradle откатился

2021-08-22 12:01 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/uml.puml
> +
это uml диаграмма, она собирается плагином plantUML

2021-08-22 12:03 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/customViews/CardView.java
> +        mbpsCaption.setText("Mbps");
да возможно стоит использовать не только `Mbps`, но это дефолтные единицы. Если надо можно сделать смену в зависимости от размерности

2021-08-22 12:06 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/customViews/CardView.java
> +    }
это для стрелочки, которой нет)) если посмотреть в фигму, то рядом с мгновенной скоростью есть стрелка upload / download
![image](https://user-images.githubusercontent.com/43898150/130354439-bf7e6274-66a8-49e1-bb1c-5ef854b489e5.png)

2021-08-22 12:31 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/customViews/CardView.java
> +        mbpsCaption.setText("Mbps");
Скорее, лучше определять в рантайме, какие единицы использовать. Например, `>= 1000` байт переходят в килобайты, `>= 1000` килобайт в мегабайты и т. д.

2021-08-22 12:35 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/uml.puml
> +
В ридми оно не используется, генерируется в рантайме. Имхо, в репозитории это хранить не надо

2021-08-22 12:39 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/SpeedManager.java
> +                return new Pair<>(int_speed, frac_speed);
это точность до 2 знаков

2021-08-22 12:41 UTC, CatherineChernogor commented on app/build.gradle
> +    ndkVersion '21.4.7075529'
в какой 19 или 21?

2021-08-22 12:41 UTC, CatherineChernogor commented on app/build.gradle
> +    ndkVersion '21.4.7075529'
в 19 или в 21?

2021-08-22 13:31 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/SpeedManager.java
> +                return new Pair<>(int_speed, frac_speed);
Понял, а в чем проблема хранить это в типе `float`?

2021-08-22 13:33 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/customViews/CardView.java
> +    }
Ну этот метод у тебя даже нигде не используется. Есть вероятность, что когда начнешь добавлять эту стрелочку, просто забудешь про этот метод.

2021-08-22 14:13 UTC, AdvancerMan commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:4.0.2'
ok

2021-08-22 14:13 UTC, AdvancerMan commented on app/build.gradle
> +    ndkVersion '21.4.7075529'
Я поправил

2021-08-22 14:23 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/customViews/CardView.java
> +    }
ок тогда уберу

2021-08-22 16:24 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +    Runnable task;
done

2021-08-22 16:25 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +    final static int TASK_DELAY = 1000;
done (private)

2021-08-22 16:34 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/SpeedManager.java
> +                return new Pair<>(int_speed, frac_speed);
там раньше был `RelativeLayout` точка выравнивалась по центру, а по точке дробная и целая часть. Так было сделано потому что futura PT не моноширинный шрифт, да и впринципе в брэнд буке сколтеха было написано что можно ил=спользовать ограниченое количество шрифтов и среди них не было ни одного моно шрифта. 

Потом я поменяла лайаут на `LinearLayout`, потому что релэйтив это уже устаревший функционал, а реализация под релэйтив так и осталась. Но вообще по хорошему это надо переписать что для мгновенной скорости, что для средней

2021-08-22 16:36 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +                Log.d("mytag", "Doing task download" + i);
done

2021-08-22 16:36 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/customButtons/SaveButton.java
> +        Log.d("mytag", "saveTask: pressed save");
done

2021-08-22 16:37 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/customViews/CardView.java
> +    String mStatus;
done

2021-08-22 16:47 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/customViews/CardView.java
> +    }
removed

2021-08-22 16:48 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/customViews/HeaderView.java
> +        });
done

2021-08-22 16:48 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/uml.puml
> +
а где тогда?

2021-08-22 16:54 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/uml.puml
> +
А зачем его вообще хранить? Если я правильно понял, он генерируется с помощью plantUML, ты его сама не пишешь. Можно же хранить только сгенерированный .png файл от него

2021-08-22 16:57 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/SpeedManager.java
> +                return new Pair<>(int_speed, frac_speed);
Даже если `RelativeLayout`. Хранить можно в дробном числе, а при отображении на экран брать только 2 знака после запятой. Делается это с помощью `String.format("%.2f")`

2021-08-22 16:58 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/SpeedManager.java
> +        View v = ((Activity) context).findViewById(R.id.result);
done

2021-08-22 17:07 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/SpeedManager.java
> +    private Pair<Integer, Integer> getAverageSpeed(List<String> list) {
done

2021-08-22 17:10 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +        handler.post(task);
это как?

2021-08-22 17:13 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/customButtons/SaveButton.java
> +                + "/Files");
done

2021-08-22 17:13 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/SpeedManager.java
> +                return new Pair<>(int_speed, frac_speed);
`Integer` занимает в [4-5 раз больше памяти](https://habr.com/ru/post/134102/), чем `int`. Еще и память на объект пары. В джаве рекоммендуется избегать `Integer` в пользу `int`

2021-08-22 17:26 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/customButtons/SaveButton.java
> +        return new File(dir.getPath() + File.separator + imageName);
`dir.getPath()` возвращает `String` , а `resolve()` это метод для типа `Path`, его просто нельзя вызывать от строки

предлагаю оставить как есть

2021-08-22 17:35 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/uml.puml
> +
я положила в корень

2021-08-22 17:51 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/SpeedManager.java
> +    private List<String> downloadList;
done

2021-08-23 05:01 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/SpeedManager.java
> +        View v = ((Activity) context).findViewById(R.id.result);
ok

2021-08-23 05:03 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/SpeedManager.java
> +    private List<String> downloadList;
ok

2021-08-23 05:03 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +    Runnable task;
ok

2021-08-23 05:03 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +    final static int TASK_DELAY = 1000;
ok

2021-08-23 05:05 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +                Log.d("mytag", "Doing task download" + i);
Тэг лучше вынести в константу

2021-08-23 05:06 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/customButtons/SaveButton.java
> +        Log.d("mytag", "saveTask: pressed save");
Тэг лучше вынести в константу

2021-08-23 05:07 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/customButtons/SaveButton.java
> +        Log.d("mytag", "saveTask: pressed save");
И еще: тэг обычно называют по имени класса

2021-08-23 05:19 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/customButtons/SaveButton.java
> +                + "/Files");
`activity.getExternalFilesDir` возвращает файл -- делаешь лишние преобразования

2021-08-23 05:20 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/customButtons/SaveButton.java
> +        return new File(dir.getPath() + File.separator + imageName);
Сорри, тогда `dir.toPath()` -- возвращает файл

2021-08-23 05:21 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/customButtons/SaveButton.java
> +        return new File(dir.getPath() + File.separator + imageName);
Ладно, `dir.toPath()` вернул бы путь, но это доступно только с апи 26

2021-08-23 05:21 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/customButtons/SaveButton.java
> +        return new File(dir.getPath() + File.separator + imageName);
ok

2021-08-23 05:21 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/customViews/CardView.java
> +    String mStatus;
ok

2021-08-23 05:21 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/customViews/CardView.java
> +    }
ok

2021-08-23 05:22 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/customViews/HeaderView.java
> +        });
ok

2021-08-23 05:25 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/uml.puml
> +
Ладно, я понял, зачем это. Лучше бы генерировать диаграмму классов по коду, а не по .puml файлу -- он быстро устаревает

2021-08-24 11:51 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +        handler.post(task);
Если еще непонятно. Я бы сделал так:
```
updateTask = new Runnable ...
finishTask = new Runnable ...
for (int i = 0; i < sm.getDownloadList().size(); i++) {
    handler.postDelayed(updateTask, MEASURING_DELAY * i);
}
handler.postDelayed(finishTask, MEASURING_DELAY * (sm.getDownloadList().size() - 1) + TASK_DELAY);
```

2021-08-24 11:51 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +        handler.post(task);
ok

2021-08-24 11:51 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +        handler.post(task);
ok

2021-08-24 15:35 UTC, merged