Bugfix and redesign
SkoltechSummerCamp/SpeedtestApplication pull request #31
Opened 2021-08-31 06:10 UTC by CatherineChernogor

- fix instant speed floating while measuring (card numbers)
- forbid landscape orientation
- fix header button icons color: now they are not violet
- fix dark theme mode
- add saving result image to gallery (Pictures directory)
- refactor iperf setting at the main screen: replace RelativeLayout with ConstraintLayout
- comment unused code in DemoActivity

2021-08-31 11:25 UTC, AdvancerMan requested changes

2021-08-31 11:25 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +        }
Копипаста (повторяется `Log.d` и `TAG`). Чтобы ее избежать + избежать свича, можно сделать через мапу. К сожалению, в той версии джавы, которую мы используем, еще не завезли `Map.of`, но у нас есть stdlib котлина.
```
map = MapsKt.mapOf(
        new kotlin.Pair<>(Configuration.UI_MODE_NIGHT_NO,  "onCreate: Light Theme"),
        ...
)
```
Потом просто `Log.d(TAG, map[currentNightMode])`

2021-08-31 11:25 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +//    private void measureDownloadSpeed() {
Хранишь мертвый код. Такой лучше сразу удалять

2021-08-31 11:25 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DevActivity.kt
> +        this.requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT
Почему бы не сделать это [в манифесте](https://stackoverflow.com/questions/9801580/screen-orientation-and-values-in-manifest-xml)? Тогда код не будет повторяться для разных активити

2021-08-31 11:25 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/customButtons/SaveButton.java
> +//        this.setBackground(AppCompatResources.getDrawable(context, R.drawable.ic_save));
Мертвый код?

2021-08-31 11:25 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/customButtons/ShareButton.kt
> +//        background = AppCompatResources.getDrawable(context, R.drawable.ic_share)
Мертвый код?

2021-08-31 15:51 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DevActivity.kt
> +        this.requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT
я когда делала через манифест у меня е работало, поэтому решила пока оставить так

2021-08-31 15:52 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/customButtons/SaveButton.java
> +//        this.setBackground(AppCompatResources.getDrawable(context, R.drawable.ic_save));
забыла убрать, уберу

2021-08-31 15:52 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/customButtons/ShareButton.kt
> +//        background = AppCompatResources.getDrawable(context, R.drawable.ic_share)
и здесь тоже

2021-08-31 17:28 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +//    private void measureDownloadSpeed() {
done, code removed

2021-08-31 17:28 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/customButtons/SaveButton.java
> +//        this.setBackground(AppCompatResources.getDrawable(context, R.drawable.ic_save));
done

2021-08-31 17:28 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/customButtons/ShareButton.kt
> +//        background = AppCompatResources.getDrawable(context, R.drawable.ic_share)
done

2021-08-31 17:35 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +        }
почему пары из котлина, в джаве же тоже есть? или это из-за того что мап из котлина и все вложенные структуры тоже должны быть котлиновскими?

2021-08-31 17:46 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +        }
fixed

2021-08-31 17:48 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DevActivity.kt
> +        this.requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT
сейчас попробую, вдруг получится переделать

2021-08-31 18:00 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DevActivity.kt
> +        this.requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT
fixed

2021-08-31 18:03 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +        }
> почему пары из котлина, в джаве же тоже есть? или это из-за того что мап из котлина и все вложенные структуры тоже должны быть котлиновскими?

1. Котлин просит свои пары в своих функциях -- другие пары -> другой класс
2. В джаве нет пар (но они есть в андроиде)

2021-08-31 18:06 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DevActivity.kt
> +        this.requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT
Вообще, я не хотел, чтобы оно дублировалось. Так оно все равно дублируется. В таком случае, что правильнее, сказать не могу

2021-08-31 18:08 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +        }
Имя лучше посодержательнее придумать. Например, `logMessages`

2021-08-31 18:09 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +//    private void measureDownloadSpeed() {
ok

2021-08-31 18:09 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DevActivity.kt
> +        this.requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT
ok

2021-08-31 18:09 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/customButtons/SaveButton.java
> +//        this.setBackground(AppCompatResources.getDrawable(context, R.drawable.ic_save));
ok

2021-08-31 18:09 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/customButtons/ShareButton.kt
> +//        background = AppCompatResources.getDrawable(context, R.drawable.ic_share)
ok

2021-08-31 18:11 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +        }
И еще, полезно ставить модификатор `final` везде, где можно. Это неявно документирует код. В андроид студии отсутствие `final` можно даже настроить как warning

2021-08-31 18:12 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +        }
После этой настройки можно будет нажимать `alt + enter` -> `fix all problems like this` и везде, где можно, будет подставляться `final`.

2021-09-01 03:56 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +        }
посмотрю что можно сделать с final

2021-09-01 03:57 UTC, CatherineChernogor commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DevActivity.kt
> +        this.requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT
> Вообще, я не хотел, чтобы оно дублировалось. Так оно все равно дублируется. В таком случае, что правильнее, сказать не могу

ну так в любом случае будет удобнее за всем следить

2021-09-01 06:59 UTC, AdvancerMan requested changes

2021-09-01 06:59 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +        // end block
Такой блок лучше сразу в отдельный метод перенести

2021-09-01 07:25 UTC, AdvancerMan commented on app/src/main/java/ru/scoltech/openran/speedtest/activities/DemoActivity.java
> +        }
ok

2021-09-02 06:48 UTC, merged